const GET_ALL_MOVIES = "APP/MOVIES/GET_ALL_MOVIES";
const GET_ONE_MOVIE = "APP/MOVIES/GET_ONE_MOVIE";
const ADD_MOVIE = "APP/MOVIES/ADD_MOVIE";
const DELETE_MOVIE = "APP/MOVIES/DELETE_MOVIE";
const PUT_MOVIE = "APP/MOVIES/UPDATE_MOVIE";

/**
 * Movies
 */
export const GET_ALL_MOVIES_REQUEST = `${GET_ALL_MOVIES}_REQUEST`;
export const GET_ALL_MOVIES_SUCCESS = `${GET_ALL_MOVIES}_SUCCESS`;
export const GET_ALL_MOVIES_FAILURE = `${GET_ALL_MOVIES}_FAILURE`;

export const GET_ONE_MOVIE_REQUEST = `${GET_ONE_MOVIE}_REQUEST`;
export const GET_ONE_MOVIE_SUCCESS = `${GET_ONE_MOVIE}_SUCCESS`;
export const GET_ONE_MOVIE_FAILURE = `${GET_ONE_MOVIE}_FAILURE`;

export const DELETE_MOVIE_REQUEST = `${DELETE_MOVIE}_REQUEST`;
export const DELETE_MOVIE_SUCCESS = `${DELETE_MOVIE}_SUCCESS`;
export const DELETE_MOVIE_FAILURE = `${DELETE_MOVIE}_FAILURE`;

export const ADD_MOVIE_REQUEST = `${ADD_MOVIE}_REQUEST`;
export const ADD_MOVIE_SUCCESS = `${ADD_MOVIE}_SUCCESS`;
export const ADD_MOVIE_FAILURE = `${ADD_MOVIE}_FAILURE`;

export const PUT_MOVIE_REQUEST = `${PUT_MOVIE}_REQUEST`;
export const PUT_MOVIE_SUCCESS = `${PUT_MOVIE}_SUCCESS`;
export const PUT_MOVIE_FAILURE = `${PUT_MOVIE}_FAILURE`;

export const CLEAR_ERROR = "CLEAR_ERROR";

export const BaseApi = "http://localhost:5000/api";
